description: This Pipeline is used to enforce the loading and exporting from and to
  NGSI-LD.
name: NGSI-LD Template Pipeline
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - transformer
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: loader
    pipelines:
    - added_at: 1741855622.191033
      pipeline:
        created_at: '2025-03-13 08:46:31.121972+00:00'
        description: null
        name: template_for_ngsi-ld
        repo_path: default_repo
        tags: []
        type: python
        uuid: template_for_ngsi_ld
      updated_at: 1741855622.191352
    retry_config: null
    status: updated
    tags: []
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: loader
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks:
    - exporter
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: transformer
    pipelines:
    - added_at: 1741855671.281296
      pipeline:
        created_at: '2025-03-13 08:46:31.121972+00:00'
        description: null
        name: template_for_ngsi-ld
        repo_path: default_repo
        tags: []
        type: python
        uuid: template_for_ngsi_ld
      updated_at: 1741855671.281462
    retry_config: null
    status: not_executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - loader
    uuid: transformer
  - all_upstream_blocks_executed: false
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: exporter
    pipelines:
    - added_at: 1741855690.850452
      pipeline:
        created_at: '2025-03-13 08:46:31.121972+00:00'
        description: null
        name: template_for_ngsi-ld
        repo_path: default_repo
        tags: []
        type: python
        uuid: template_for_ngsi_ld
      updated_at: 1741855690.850599
    retry_config: null
    status: updated
    tags: []
    timeout: null
    type: data_exporter
    upstream_blocks:
    - transformer
    uuid: exporter
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2025-03-13 08:46:31.121972+00:00'
  data_integration: null
  description: null
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: template_for_ngsi-ld
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers: null
  spark_config: {}
  tags: []
  type: python
  uuid: ngsi_ld
  variables_dir: /home/src/mage_data/default_repo
  widgets: []
tags: []
user:
  username: admin
