default:
  ALGOLIA_API_KEY: api_key
  ALGOLIA_APP_ID: app_id
  ALGOLIA_INDEX_NAME: index_name
  AWS_ACCESS_KEY_ID: super
  AWS_REGION: region
  AWS_SECRET_ACCESS_KEY: doopersecret
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  GOOGLE_LOCATION: US
  GOOGLE_SERVICE_ACC_KEY:
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    auth_uri: https://accounts.google.com/o/oauth2/auth
    client_email: your_service_account_email
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email
    private_key: '-----BEGIN PRIVATE KEY-----

      your_private_key

      -----END_PRIVATE_KEY'
    private_key_id: key-id
    project_id: project-id
    token_uri: https://accounts.google.com/o/oauth2/token
    type: service_account
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: /path/to/your/service/account/key.json
  MINIO_ACCESS_KEY: super
  MINIO_API: https://ingress.sedimark.work/balancer
  MINIO_BUCKET_NAME: dataspace
  MINIO_HOST: minio1.sedimark.work
  MINIO_PORT: 9000
  MINIO_SECRET_KEY: doopersecret
  MLFLOW_S3_ENDPOINT_URL: https://minio1.sedimark.work
  MLFLOW_TRACKING_INSECURE_TLS: 'true'
  MLFLOW_TRACKING_PASSWORD: password
  MLFLOW_TRACKING_USERNAME: admin
  MONGODB_COLLECTION: collection
  MONGODB_CONNECTION_STRING: mongodb://{username}:{password}@{host}:{port}/
  MONGODB_DATABASE: database
  MONGODB_HOST: host
  MONGODB_PASSWORD: password
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MSSQL_DATABASE: database
  MSSQL_DRIVER: ODBC Driver 18 for SQL Server
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_SCHEMA: schema
  MSSQL_USER: SA
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: pfmegrnargs
  POSTGRES_HOST: hh-pgsql-public.ebi.ac.uk
  POSTGRES_PASSWORD: NWDMCE5xdipIjRrp
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: public
  POSTGRES_USER: reader
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_IAM_PROFILE: default
  REDSHIFT_PORT: 5439
  REDSHIFT_SCHEMA: public
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_TEMP_CRED_USER: temp_username
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_DB: null
  SNOWFLAKE_DEFAULT_SCHEMA: null
  SNOWFLAKE_DEFAULT_WH: null
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null
  SNOWFLAKE_PRIVATE_KEY_PATH: null
  SNOWFLAKE_ROLE: null
  SNOWFLAKE_TIMEOUT: null
  SNOWFLAKE_USER: username
  WEAVIATE_COLLECTION: collectionn_name
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  trino:
    catalog: postgresql
    host: 127.0.0.1
    http_headers:
      X-Something: mage=power
    http_scheme: http
    password: mage1337
    port: 8080
    schema: core_data
    session_properties:
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli
    user: admin
    verify: /path/to/your/ca.crt
version: 0.1.1
