description: '{

  "type": "data_models"

  "description" : "Anomaly annotator pipeline"

  }'
name: 'Basic Template '
pipeline:
  blocks:
  - all_upstream_blocks_executed: true
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration:
      entity_id: '{     "type": "drop_down",     "description": "This is the ID of
        the entity that is stored in the NGSI-LD Broker",     "values": ["urn:ngsi-ld:WeatherInformation:Forecasted:Hourly:France:Les_Orres"]
        }'
      load_date: '{     "type": "date",     "description": "The date after which the
        data from the broker will be loaded!",     "format": "YYYY-MM-DD" }'
    downstream_blocks:
    - anomaly_detection
    - histogram_for_broker_loader_1707813944696
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: broker_loader
    pipelines:
    - added_at: null
      pipeline:
        created_at: '2023-11-14 11:26:30.357670+00:00'
        description: data_preprocessing
        name: anomaly_annotator
        repo_path: default_repo
        tags:
        - data_preprocessing
        type: python
        uuid: anomaly_annotator
      updated_at: 1750659620.545837
    - added_at: null
      pipeline:
        created_at: '2023-09-19 11:10:36.692226+00:00'
        description: 'pipeline that uses data from stellio broker and trains the model,
          saves it to minio and then predicts data based on the saved model

          -OLD'
        name: mlflow train_test
        repo_path: default_repo
        tags: []
        type: python
        uuid: mlflow_train_test
      updated_at: 1750659620.547539
    - added_at: null
      pipeline:
        created_at: '2024-09-23 19:31:56.239782+00:00'
        description: null
        name: surrey
        repo_path: default_repo
        tags: []
        type: python
        uuid: surrey
      updated_at: 1750659620.554213
    retry_config: {}
    status: executed
    tags: []
    timeout: null
    type: data_loader
    upstream_blocks: []
    uuid: broker_loader
  - all_upstream_blocks_executed: true
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration:
      threshold_type: '{     "type": "drop_down",     "description": "This is the
        threshold type for the anomaly detection algorithm.",     "values": [         "AUCP",         "contamination"     ]
        }'
    downstream_blocks:
    - export_anomalies
    - bar_chart_for_anomaly_detection_1707814173891
    - pie_chart_for_anomaly_detection_1707814210425
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: anomaly_detection
    pipelines:
    - added_at: null
      pipeline:
        created_at: '2023-11-14 11:26:30.357670+00:00'
        description: data_preprocessing
        name: anomaly_annotator
        repo_path: default_repo
        tags:
        - data_preprocessing
        type: python
        uuid: anomaly_annotator
      updated_at: 1750659620.546483
    retry_config: {}
    status: executed
    tags: []
    timeout: null
    type: transformer
    upstream_blocks:
    - broker_loader
    uuid: anomaly_detection
  - all_upstream_blocks_executed: true
    callback_blocks: []
    color: null
    conditional_blocks: []
    configuration: {}
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    metadata: {}
    name: export_anomalies
    pipelines:
    - added_at: null
      pipeline:
        created_at: '2023-11-14 11:26:30.357670+00:00'
        description: data_preprocessing
        name: anomaly_annotator
        repo_path: default_repo
        tags:
        - data_preprocessing
        type: python
        uuid: anomaly_annotator
      updated_at: 1750659620.54682
    retry_config: {}
    status: failed
    tags: []
    timeout: null
    type: data_exporter
    upstream_blocks:
    - anomaly_detection
    uuid: export_anomalies
  cache_block_output_in_memory: false
  callbacks: []
  concurrency_config: {}
  conditionals: []
  created_at: '2023-11-14 11:26:30.357670+00:00'
  data_integration: null
  description: data_preprocessing
  executor_config: {}
  executor_count: 1
  executor_type: null
  extensions: {}
  name: anomaly_annotator
  notification_config: {}
  remote_variables_dir: null
  retry_config: {}
  run_pipeline_in_one_process: false
  settings:
    triggers:
      save_in_code_automatically: true
  spark_config: {}
  tags:
  - data_preprocessing
  type: python
  uuid: basic_template
  variables_dir: /home/src/mage_data/default_repo
  widgets:
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      buckets: 10
      chart_type: line chart
      x: x
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: histogram for broker_loader 1707813944696
    retry_config: null
    status: executed
    timeout: null
    type: chart
    upstream_blocks:
    - broker_loader
    uuid: histogram_for_broker_loader_1707813944696
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      chart_style: vertical
      chart_type: pie chart
      x: x
      y: y
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: bar chart for anomaly_detection 1707814173891
    retry_config: null
    status: executed
    timeout: null
    type: chart
    upstream_blocks:
    - anomaly_detection
    uuid: bar_chart_for_anomaly_detection_1707814173891
  - all_upstream_blocks_executed: true
    color: null
    configuration:
      buckets: 7
      chart_type: pie chart
      x: x
    downstream_blocks: []
    executor_config: null
    executor_type: local_python
    has_callback: false
    language: python
    name: pie chart for anomaly_detection 1707814210425
    retry_config: null
    status: executed
    timeout: null
    type: chart
    upstream_blocks:
    - anomaly_detection
    uuid: pie_chart_for_anomaly_detection_1707814210425
tags: []
user:
  username: admin
