triggers:
- envs: []
  last_enabled_at: 2024-05-17 08:22:22.947156
  name: anomaly_annotator_trigger
  pipeline_uuid: anomaly_annotator
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-05-17 08:22:00
  status: active
  variables: {}
