name: Create Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    timeout-minutes: 720
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set image tag
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH" == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Kaniko build & push
        uses: aevea/action-kaniko@master
        with:
          image: sedimark-mage
          cache: "false"
          tag: ${{ env.IMAGE_TAG }}
          path: .
          debug: true
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          extra_args: --snapshot-mode=time
